### ISSUE TITLE
Never leaves the peer network

### ISSUE THREAD

**Issue by slaskis** [mafintosh/peer-network#2]
I've been playing around a bit with this really cool module and noticed that it never leaves the peer network. 

So I've made a simple cli which pipes to stdout on listen and stdin on connect. The listening server joins the discover channel but never leaves so when restarting a few times with the same network name it now has 100s of peers stored but only the last one will actually connect.

I know you just published it and don't expect it to be perfect already, but just thought I'd post my findings.

Thanks for this, it's super interesting to use a global name for a server without DNS!

**Comment by mafintosh** [comment]
Does your server listen on a new port each time or do you set the port argument?

**Comment by slaskis** [comment]
I don't specify any port so it's a new port every time. 

I've published the code here https://github.com/slaskis/peercat/

**Comment by mafintosh** [comment]
ah cool, yea its not always possible to unannounce so a good pattern is to do

``` js
server.once('error', function (err) {
  // assume port in use
  server.listen('some-name')
})
server.listen('some-name', 5000) // 5000 is arbitrary to some static port
```

we should update the readme to include that (and of course make unannounce better internally)

**Comment by slaskis** [comment]
ah I see, so it wouldn't be good enough to do something like this in `Network#createServer`:

```
server.on('close', () => this.discovery.leave(this.name))
```

What would be the benefit of leaving the server port/host in discovery while it's shut down? Or is it just a matter of not being able to leave reliably when the process exits?

**Comment by mafintosh** [comment]
no we should do that no matter what :) but in general relying on cleanup code is tricky in distributed system so i'd reuse the port if i could

**Comment by mafintosh** [comment]
1.2.0 picks consistent random ports now using https://github.com/mafintosh/hash-to-port so you'll get fewer dht entries

**Comment by mafintosh** [comment]
and server.close() unannounces

**Comment by slaskis** [comment]
Great, thanks!
